[package]
authors.workspace      = true
categories             = ["command-line-utilities"]
description            = "The official command line client for interacting with the Miden rollup"
documentation          = "https://docs.rs/miden-client-cli/0.10.0"
edition.workspace      = true
keywords               = ["cli", "client", "miden"]
license.workspace      = true
name                   = "miden-client-cli"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.10.0"

[[bin]]
name = "miden-client"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = []

[[test]]
name = "integration"
path = "tests/cli.rs"

[dev-dependencies]
assert_cmd = { version = "2.0" }
predicates = { version = "3.0" }
uuid       = { features = ["serde", "v4"], version = "1.10" }

[dependencies]
clap               = { features = ["derive"], version = "4.5" }
comfy-table        = { version = "7.1" }
figment            = { features = ["env", "toml"], version = "0.10" }
miden-client       = { features = ["sqlite", "tonic"], path = "../../crates/rust-client", version = "0.10" }
miden-lib          = { workspace = true }
miden-objects      = { workspace = true }
miette             = { workspace = true }
rand               = { workspace = true }
serde              = { features = ["derive"], version = "1.0" }
thiserror          = { workspace = true }
tokio              = { workspace = true }
toml               = { version = "0.8" }
tracing            = { workspace = true }
tracing-subscriber = { version = "0.3" }

[build-dependencies]
miden-client  = { path = "../../crates/rust-client", version = "0.10" }
miden-lib     = { workspace = true }
miden-objects = { workspace = true }
